apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: marco-polo
  name: marco-polo
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: marco-polo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marco-polo
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/sampsoftware/demo-apps/marco-polo
        name: marco-polo
        ports:
        - containerPort: 8080
          name: http-web-svc
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      imagePullSecrets:
      - name: gcp-artifact-sampsoftware


---
apiVersion: v1
kind: Service
metadata:
  name: marco-polo
spec:
  selector:
    app.kubernetes.io/name: marco-polo
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
  type: LoadBalancer
